"""empty message

Revision ID: dfd804ecfef4
Revises: 
Create Date: 2022-10-09 20:56:24.112754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd804ecfef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_name', sa.String(length=150), nullable=True),
    sa.Column('usr_password', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
